(function () {
  'use strict';

  const translations = {
    "Home": "Início",
    "World Cup 2026": "Copa do Mundo 2026",
    "Products": "Produtos",
    "Why Us / Reviews": "Por que escolher / Avaliações",
    "Company / Certifications": "Empresa / Certificações",
    "3-Level QC / After-Sales": "Controle de qualidade em 3 etapas / Pós-venda",
    "After-Sales Lookup": "Consulta pós-venda",
    "WhatsApp": "WhatsApp",
    "May 12-31 · Order +200 pcs · 15% OFF on Mundial 2026": "12 a 31 de maio · Pedido +200 peças · 15% OFF no Mundial 2026",
    "Grab now →": "Aproveitar agora →",
    "NEW COLLECTION · 2026": "NOVA COLEÇÃO · 2026",
    "Jerseys · Collectibles · Official Souvenirs": "Camisas · Colecionáveis · Souvenires oficiais",
    "269 products from Mundial Mexico-USA-Canada: 32 national team jerseys, vintage, mascot plush, mystery boxes and keychains.": "269 produtos do Mundial México-EUA-Canadá: camisas de 32 seleções, modelos vintage, mascotes de pelúcia, caixas-surpresa e chaveiros.",
    "Days": "Dias",
    "See Full Catalog": "Ver catálogo completo",
    "G5 Supply Chain — Direct Pricing + Local Warehouse": "Cadeia de suprimentos G5 — Preço direto + estoque local",
    "G5 supply chain: direct factory pricing, local warehouse and after-sales support": "Cadeia de suprimentos G5: preço direto de fábrica, estoque local e suporte pós-venda",
    "We integrate G5 suppliers to offer direct pricing with no middlemen, local warehouse dispatch with 3-day response, and quality control on every batch.": "Integramos fornecedores G5 para oferecer preços diretos, sem intermediários, envio a partir do estoque local com resposta em até 3 dias e controle de qualidade em cada lote.",
    "Direct pricing": "Preço direto",
    "Fast support": "Suporte rápido",
    "Warehouse + after-sales": "Estoque + pós-venda",
    "Your trusted G5 supply partner for <em>online and offline sales</em>": "Seu parceiro G5 de confiança para <em>vendas online e offline</em>",
    "G5 factory-direct pricing · Local warehouse with fast dispatch · OEM packaging · 3-stage QC · DDP delivery in 5–7 days.": "Preço direto de fábrica G5 · Estoque local com envio rápido · Embalagem OEM · Controle de qualidade em 3 etapas · Entrega DDP em 5–7 dias.",
    "View B2B Catalog": "Ver catálogo B2B",
    "Request a Quote": "Solicitar cotação",
    "View Client Reviews": "Ver avaliações de clientes",
    "B2B Clients": "Clientes B2B",
    "Countries": "Países",
    "Units / month": "Unidades / mês",
    "Drag to rotate": "Arraste para girar",
    "avg. damage": "avarias em média",
    "fast mockup": "mockup rápido",
    "delivery": "entrega",
    "Deep ANC": "ANC avançado",
    "Spatial audio": "Áudio espacial",
    "Powerful bass": "Graves potentes",
    "Touch control": "Controle por toque",
    "Years Exporting": "Anos exportando",
    "Active B2B Clients": "Clientes B2B ativos",
    "Export Countries": "Países atendidos",
    "Units per Month": "Unidades por mês",
    "Global Certifications": "Certificações globais",
    "Min. Order (units)": "Pedido mínimo (unidades)",
    "CATALOG": "CATÁLOGO",
    "Featured Products": "Produtos em destaque",
    "Premium electronics curated for distributors. Every product passes 3-stage quality inspection.": "Eletrônicos premium selecionados para distribuidores. Todos os produtos passam por uma inspeção de qualidade em 3 etapas.",
    "AirPods, watches, Dyson, power banks and charging kits": "AirPods, relógios, Dyson, power banks e kits de carregamento",
    "Sneakers, apparel, jerseys and brand collections": "Tênis, roupas, camisas e coleções por marca",
    "Jerseys, national teams and campaign promotion": "Camisas, seleções e produtos promocionais",
    "Electronics categories": "Categorias de eletrônicos",
    "Watches": "Relógios",
    "Power Banks": "Power banks",
    "Charging Kit": "Kit de carregamento",
    "Lifestyle": "Estilo de vida",
    "Security Cam.": "Câmeras de segurança",
    "Sports Cam.": "Câmeras esportivas",
    "GLOBAL REACH": "PRESENÇA GLOBAL",
    "Connecting China to the World": "Conectando a China ao mundo",
    "Three strategically located warehouses to serve each region with fast local delivery.": "Três centros de distribuição estrategicamente localizados para atender cada região com entrega local rápida.",
    "5-7 days to all Latin America": "5–7 dias para toda a América Latina",
    "2-3 days to all Europe": "2–3 dias para toda a Europa",
    "Fast dispatch across ASEAN": "Envio rápido para toda a ASEAN",
    "PROCESS": "PROCESSO",
    "How It Works": "Como funciona",
    "Simple 6-step process from selection to delivery.": "Processo simples em 6 etapas, da seleção à entrega.",
    "Select": "Selecionar",
    "Browse catalog": "Explorar o catálogo",
    "Quote": "Cotação",
    "Confirm with sales": "Confirmar com a equipe de vendas",
    "Packaging": "Embalagem",
    "Customization": "Personalização",
    "Payment": "Pagamento",
    "Local transfer": "Transferência local",
    "Shipping": "Envio",
    "5-7 days DDP": "5–7 dias DDP",
    "Delivery": "Entrega",
    "Receive goods": "Receber a mercadoria",
    "BUYER SUPPORT": "SUPORTE AO COMPRADOR",
    "Support before and after every order": "Suporte antes e depois de cada pedido",
    "After product selection, our team helps confirm variant, packaging, logistics and replenishment so you can sell with less risk.": "Após a escolha do produto, nossa equipe ajuda a confirmar a versão, a embalagem, a logística e a reposição para que você venda com menos risco.",
    "A buying list built for your channel": "Uma lista de compras pensada para o seu canal",
    "Tell us your country, budget and sales channel. We recommend fast-moving models, starting quantities, suitable packaging and shipping method. This helps avoid slow inventory and improves resale speed.": "Informe seu país, orçamento e canal de vendas. Recomendamos modelos de alta rotatividade, quantidades iniciais, embalagem adequada e forma de envio. Isso ajuda a evitar estoque parado e acelera a revenda.",
    "Samples & selection": "Amostras e seleção",
    "Confirm quality, features and version before scaling the order.": "Confirme a qualidade, os recursos e a versão antes de aumentar o pedido.",
    "Retail-ready packaging": "Embalagem pronta para o varejo",
    "Logo, label, manual and sticker for your market.": "Logo, etiqueta, manual e adesivo adequados ao seu mercado.",
    "Batch control": "Controle por lote",
    "Functional and visual inspection before shipping.": "Inspeção funcional e visual antes do envio.",
    "Simple reorder": "Reposição simplificada",
    "We keep your models, packaging and logistics preference.": "Mantemos registrados seus modelos e suas preferências de embalagem e logística.",
    "Back to Products": "Voltar aos produtos",
    "Back to Home": "Voltar ao início",
    "ABOUT US": "SOBRE NÓS",
    "About Us": "Sobre nós",
    "Certifications": "Certificações",
    "Team": "Equipe",
    "Professional Smart Device Manufacturer": "Fabricante profissional de dispositivos inteligentes",
    "Integrating R&amp;D, production, and sales. From Guangzhou to the world.": "Integramos P&amp;D, produção e vendas. De Guangzhou para o mundo.",
    "m² Industrial Park": "m² de parque industrial",
    "Employees": "Funcionários",
    "Solution Specialists": "Especialistas em soluções",
    "R&amp;D Specialists": "Especialistas em P&amp;D",
    "<strong>Guangzhou Miravue Trading Co., Ltd. (广州市千幻贸易有限公司)</strong> is a smart-device supply chain company integrating solution development, procurement, processing, and sales. We operate a 20,000-square-meter industrial park with more than 200 employees, including 35 solution specialists and 20 R&amp;D professionals.": "A <strong>Guangzhou Miravue Trading Co., Ltd. (广州市千幻贸易有限公司)</strong> é uma empresa da cadeia de suprimentos de dispositivos inteligentes que integra desenvolvimento de soluções, compras, processamento e vendas. Operamos um parque industrial de 20.000 m² com mais de 200 funcionários, incluindo 35 especialistas em soluções e 20 profissionais de P&amp;D.",
    "Our customization, sales, and after-sales departments allow us to provide tailored solutions for different customers. We combine OEM/ODM support, cost control, quality inspection, warehousing, and logistics coordination to support each order from product selection through delivery.": "Nossos departamentos de personalização, vendas e pós-venda nos permitem oferecer soluções sob medida para diferentes clientes. Combinamos suporte OEM/ODM, controle de custos, inspeção de qualidade, armazenagem e coordenação logística para acompanhar cada pedido, da seleção do produto à entrega.",
    "With market experience across Europe, Southeast Asia, and South America, our products are exported to markets in Asia, Europe, North America, South America, and Africa. We remain committed to continuously improving product quality, service, and communication with our international partners.": "Com experiência de mercado na Europa, no Sudeste Asiático e na América do Sul, nossos produtos são exportados para a Ásia, Europa, América do Norte, América do Sul e África. Mantemos o compromisso de melhorar continuamente a qualidade dos produtos, o atendimento e a comunicação com nossos parceiros internacionais.",
    "Certifications &amp; Quality": "Certificações e qualidade",
    "We meet the highest international standards.": "Atendemos aos mais altos padrões internacionais.",
    "Our Team": "Nossa equipe",
    "Hand in Hand, We Create Brilliance Together.": "Juntos, criamos resultados extraordinários.",
    "Our Philosophy": "Nossa filosofia",
    "&ldquo;Striving for excellence and perfection&rdquo; — We strictly control every production stage to ensure stable and reliable quality.": "&ldquo;Buscamos excelência e perfeição&rdquo; — Controlamos rigorosamente cada etapa da produção para garantir qualidade estável e confiável.",
    "Team Spirit": "Espírito de equipe",
    "&ldquo;Hand in Hand, We Create Brilliance Together&rdquo; — Collaboration and dedication drive us to deliver the best to our global partners.": "&ldquo;Juntos, criamos resultados extraordinários&rdquo; — Colaboração e dedicação nos impulsionam a entregar o melhor aos nossos parceiros globais.",
    "CONTACT": "CONTATO",
    "Get in Touch": "Entre em contato",
    "Start your inquiry today. We respond within 2 hours.": "Envie sua consulta hoje. Respondemos em até 2 horas.",
    "Contact Information": "Informações de contato",
    "Our team is ready to help with your order.": "Nossa equipe está pronta para ajudar com seu pedido.",
    "Address": "Endereço",
    "Follow us on social media": "Siga-nos nas redes sociais",
    "Request Information": "Solicitar informações",
    "Full Name *": "Nome completo *",
    "Company *": "Empresa *",
    "Country *": "País *",
    "Phone/WhatsApp *": "Telefone/WhatsApp *",
    "Email": "E-mail",
    "Products of Interest": "Produtos de interesse",
    "Message": "Mensagem",
    "Submit Inquiry": "Enviar consulta",
    "WHY US": "POR QUE NOS ESCOLHER",
    "Why Choose Us": "Por que escolher a Miravue",
    "Reviews & Testimonials": "Avaliações e depoimentos",
    "Your Reliable Export Partner": "Seu parceiro de exportação confiável",
    "6 reasons why distributors in 30+ countries choose us.": "6 motivos pelos quais distribuidores de mais de 30 países nos escolhem.",
    "Security Assurance": "Garantia de segurança",
    "3-stage QC. Every batch tested before shipment.": "Controle de qualidade em 3 etapas. Todos os lotes são testados antes do envio.",
    "OEM/ODM Support": "Suporte OEM/ODM",
    "Custom branding, packaging, and product design.": "Marca, embalagem e design de produto personalizados.",
    "Cost Control": "Controle de custos",
    "Competitive factory-direct pricing from Shenzhen.": "Preços competitivos direto da fábrica em Shenzhen.",
    "Dedicated Service": "Atendimento dedicado",
    "2-hour response. Account manager for every partner.": "Resposta em até 2 horas. Gerente de conta para cada parceiro.",
    "Local Warehousing": "Estoque local",
    "Ready stock in Brazil, Germany, and Thailand.": "Estoque disponível no Brasil, Alemanha e Tailândia.",
    "CE, FCC, RoHS, ISO 9001. Full import compliance.": "CE, FCC, RoHS e ISO 9001. Conformidade completa para importação.",
    "What Our Clients Say": "O que nossos clientes dizem",
    "Real distributors, real results. This section now combines testimonials, visual proof and recommendation letters to build more trust.": "Distribuidores reais, resultados reais. Esta seção reúne depoimentos, provas visuais e cartas de recomendação para transmitir ainda mais confiança.",
    "B2B clients": "Clientes B2B",
    "Countries served": "Países atendidos",
    "DDP days": "Dias DDP",
    "Damage rate": "Índice de avarias",
    "Resale": "Revenda",
    "Here in Mexico, earphones with this quality cost double or triple. I will order again for resale because my clients loved them.": "Aqui no México, fones com essa qualidade custam o dobro ou o triplo. Vou fazer novos pedidos para revenda porque meus clientes adoraram.",
    "Importer, Mexico": "Importador, México",
    "The Brazil warehouse cut our lead time from 35 to 5 days. Great quality and constant communication throughout the order.": "O estoque no Brasil reduziu nosso prazo de 35 para 5 dias. Ótima qualidade e comunicação constante durante todo o pedido.",
    "Importer, Brazil": "Importador, Brasil",
    "Service": "Atendimento",
    "Excellent service. The account manager answered my questions within minutes and products arrived in perfect condition.": "Atendimento excelente. O gerente de conta respondeu às minhas dúvidas em poucos minutos e os produtos chegaram em perfeito estado.",
    "Importer, Colombia": "Importador, Colômbia",
    "REAL LETTERS & SCREENSHOTS": "CARTAS E CAPTURAS REAIS",
    "More proof, fewer promises": "Mais provas, menos promessas",
    "Beyond written reviews, we show screenshots, letters and client conversations so new buyers understand how we work before, during and after the order.": "Além das avaliações escritas, mostramos capturas de tela, cartas e conversas com clientes para que novos compradores entendam como trabalhamos antes, durante e depois do pedido.",
    "QUALITY CONTROL": "CONTROLE DE QUALIDADE",
    "3-Level Verification System": "Sistema de verificação em 3 etapas",
    "Every product passes through three inspection layers before reaching you. Our damage rate is below <strong style='color:var(--accent-moss)'>0.3%</strong> — the lowest in the industry.": "Todos os produtos passam por três níveis de inspeção antes de chegar até você. Nosso índice de avarias é inferior a <strong style='color:var(--accent-moss)'>0,3%</strong> — um dos menores do setor.",
    "Factory Inspection": "Inspeção na fábrica",
    "100% functional test (sound, mic, buttons)": "Teste funcional em 100% das unidades (som, microfone e botões)",
    "Assembly QC (fit, solder, finish)": "Controle da montagem (encaixe, solda e acabamento)",
    "Visual inspection of housing & packaging": "Inspeção visual do produto e da embalagem",
    "Lab Testing": "Testes de laboratório",
    "Battery test (actual capacity, charge cycles)": "Teste da bateria (capacidade real e ciclos de carga)",
    "Bluetooth connection stability test": "Teste de estabilidade da conexão Bluetooth",
    "Durability test (drop, buttons, connector)": "Teste de durabilidade (queda, botões e conector)",
    "Random batch sampling (AQL 2.5)": "Amostragem aleatória por lote (AQL 2,5)",
    "Third-Party Audit": "Auditoria independente",
    "Pre-shipment inspection by independent agency": "Inspeção pré-embarque por empresa independente",
    "Certification verification (CE, FCC, RoHS, ISO 9001)": "Verificação das certificações (CE, FCC, RoHS e ISO 9001)",
    "Inspection report available upon request": "Relatório de inspeção disponível mediante solicitação",
    "AFTER-SALES GUARANTEE": "GARANTIA PÓS-VENDA",
    "Warranty & After-Sales Service Policy": "Política de garantia e atendimento pós-venda",
    "Full commitment to quality. Damage rate below <strong style='color:var(--accent-moss)'>0.3%</strong>.": "Compromisso total com a qualidade. Índice de avarias inferior a <strong style='color:var(--accent-moss)'>0,3%</strong>.",
    "If the product cannot be used or lacks functionality, we can <strong>refund the price difference on your next order</strong> or <strong>replace it free of charge</strong>. Our damage rate is below <strong style='color:var(--accent-moss)'>0.3%</strong>, the lowest in the industry. We rigorously control every production stage to ensure maximum quality.": "Se o produto não puder ser usado ou apresentar falha funcional, podemos <strong>creditar o valor no seu próximo pedido</strong> ou <strong>substituí-lo gratuitamente</strong>. Nosso índice de avarias é inferior a <strong style='color:var(--accent-moss)'>0,3%</strong>, um dos menores do setor. Controlamos rigorosamente todas as etapas da produção para garantir a máxima qualidade.",
    "<strong>Warranty coverage:</strong> 30 calendar days from receipt of goods. We cover manufacturing defects, functional failures, and shipping damage. Does not cover misuse or normal wear and tear.": "<strong>Cobertura da garantia:</strong> 30 dias corridos a partir do recebimento da mercadoria. Cobrimos defeitos de fabricação, falhas funcionais e danos no transporte. Não cobrimos uso indevido nem desgaste normal.",
    "<strong>Claim process:</strong> Send a photo or video of the defective product to your account manager via WhatsApp. We process your claim within 24 hours. Refund or replacement is handled on your next order with no additional shipping cost.": "<strong>Processo de solicitação:</strong> Envie uma foto ou vídeo do produto com defeito ao seu gerente de conta pelo WhatsApp. Processamos a solicitação em até 24 horas. O crédito ou a substituição é incluído no próximo pedido, sem custo adicional de envio.",
    "Refund or Replace": "Crédito ou substituição",
    "No extra cost": "Sem custo adicional",
    "< 0.3% Damage Rate": "< 0,3% de avarias",
    "Lowest in the industry": "Um dos menores do setor",
    "Insured Shipping": "Envio com seguro",
    "100% DDP coverage": "Cobertura DDP completa",
    "24h Response": "Resposta em 24 h",
    "Fast processing": "Processamento rápido",
    "AFTER-SALES LOOKUP": "CONSULTA PÓS-VENDA",
    "Warranty Status Lookup": "Consulta do status da garantia",
    "Enter your order details to check your warranty status.": "Informe os dados do pedido para consultar o status da garantia.",
    "Order / Invoice Number *": "Número do pedido / fatura *",
    "Logistics Tracking Number *": "Código de rastreamento *",
    "Ship Date *": "Data de envio *",
    "Phone / WhatsApp *": "Telefone / WhatsApp *",
    "Damaged Product Serial Number *": "Número de série do produto com defeito *",
    "Product Name *": "Nome do produto *",
    "Problem Description": "Descrição do problema",
    "Check Status": "Consultar status",
    "Querying database...": "Consultando o banco de dados...",
    "Product information not found": "Informações do produto não encontradas",
    "We temporarily cannot find your product data. Please contact our support team via WhatsApp for immediate assistance.": "No momento, não encontramos os dados do seu produto. Entre em contato com nossa equipe pelo WhatsApp para receber atendimento imediato.",
    "Contact Support via WhatsApp": "Falar com o suporte pelo WhatsApp",
    "Premium consumer electronics for global distributors.": "Eletrônicos premium para distribuidores globais.",
    "Local after-sales": "Pós-venda local",
    "Office map: Baiyun District, Guangzhou": "Mapa do escritório: distrito de Baiyun, Guangzhou",
    "Company": "Empresa",
    "Support": "Suporte",
    "My Inquiry": "Minha cotação",
    "Total items:": "Total de itens:",
    "Send via WhatsApp": "Enviar pelo WhatsApp",
    "Keep Browsing": "Continuar explorando",
    "Shipping Address": "Endereço de entrega",
    "— Country *": "— País *",
    "— State *": "— Estado *",
    "Please fill in Country, State, City and Postal Code.": "Preencha país, estado, cidade e CEP.",
    "Under Maintenance": "Em manutenção",
    "The Putian Fashion section is temporarily under maintenance. Check back soon or contact us on WhatsApp for more info.": "A seção Putian Fashion está temporariamente em manutenção. Volte em breve ou fale conosco pelo WhatsApp para mais informações.",
    "Go Back": "Voltar",
    "MOQ: 50 PCS": "MOQ: 50 peças",
    "View Detail": "Ver detalhes",
    "Video": "Vídeo",
    "Normal": "Normal",
    "Standard": "Padrão",
    "OEM Custom": "OEM personalizado",
    "(50 PCS)": "(50 peças)",
    "(120 PCS+)": "(120 peças+)",
    "Estimated Total": "Total estimado",
    "USD · Quote Price": "BRL · Preço estimado",
    "Quantity": "Quantidade",
    "Recommended: 50+ units": "Recomendado: 50+ unidades",
    "Calculate Shipping": "Calcular frete",
    "Add to Inquiry": "Adicionar à cotação",
    "New collection available": "Nova coleção disponível",
    "Starts in": "Começa em",
    "days": "dias",
    "Explore now →": "Explorar agora →",
    "e.g. HY-2026-05001": "Ex.: HY-2026-05001",
    "Tracking / waybill number": "Código de rastreamento",
    "+1 555 XXXX": "+55 (11) 9XXXX-XXXX",
    "SN / IMEI of defective product": "SN / IMEI do produto com defeito",
    "Product name": "Nome do produto",
    "Briefly describe the product issue...": "Descreva brevemente o problema do produto...",
    "City *": "Cidade *",
    "Postal Code *": "CEP *",
    "Full Address": "Endereço completo",
    "Contact Name": "Nome do contato",
    "Chip": "Chip",
    "Bluetooth": "Bluetooth",
    "Mode": "Modo",
    "Cable": "Cabo",
    "Shell": "Carcaça",
    "Battery": "Bateria",
    "Battery Life": "Autonomia da bateria",
    "Features": "Recursos",
    "App": "Aplicativo",
    "Screen": "Tela",
    "Product Description": "Descrição do produto",
    "Function Description": "Descrição das funções",
    "APP backend": "Backend do aplicativo",
    "Material": "Material",
    "Battery Capacity": "Capacidade da bateria",
    "Screen Resolution": "Resolução da tela",
    "Single Package Size": "Tamanho da embalagem individual",
    "Single Weight": "Peso unitário",
    "Motor": "Motor",
    "Power": "Potência",
    "Modes": "Modos",
    "Model": "Modelo",
    "Suction": "Sucção",
    "Filter": "Filtro",
    "Runtime": "Autonomia",
    "Color": "Cor",
    "Design": "Design",
    "strap": "pulseira",
    "dial": "mostrador",
    "Metal frame": "Estrutura metálica",
    "PC base": "Base em PC",
    "PC cover": "Tampa em PC",
    "TPU strap": "Pulseira de TPU",
    "Silicone strap": "Pulseira de silicone",
    "Stainless steel strap": "Pulseira de aço inoxidável",
    "Milanese strap": "Pulseira milanesa",
    "Steel strap": "Pulseira de aço",
    "Leather strap": "Pulseira de couro",
    "Black": "Preto",
    "White": "Branco",
    "Silver": "Prata",
    "Gold": "Dourado",
    "Pink": "Rosa",
    "Blue": "Azul",
    "Orange": "Laranja",
    "Red": "Vermelho",
    "Gray": "Cinza",
    "Green": "Verde",
    "Purple": "Roxo",
    "Brown": "Marrom",
    "Single color": "Uma cor",
    "Two-tone": "Duas cores",
    "Metal + leather": "Metal + couro",
    "Full features": "Recursos completos",
    "Charging": "Carregamento",
    "Wireless charging": "Carregamento sem fio",
    "Heart rate": "Frequência cardíaca",
    "Blood pressure": "Pressão arterial",
    "Blood oxygen": "Oxigênio no sangue",
    "Pedometer": "Pedômetro",
    "Sleep": "Sono",
    "Bluetooth calls": "Chamadas Bluetooth",
    "Music player": "Reprodutor de música",
    "Multi-sport modes": "Modos multiesportivos",
    "Raise to wake": "Acender ao levantar o pulso",
    "Flip to wake": "Acender ao girar o pulso",
    "Sedentary reminder": "Lembrete de sedentarismo",
    "Alarm": "Alarme",
    "Remote camera": "Câmera remota",
    "Notifications": "Notificações",
    "Weather": "Clima",
    "Custom wallpaper": "Papel de parede personalizado",
    "Multi-language": "Vários idiomas",
    "Voice assistant": "Assistente de voz",
    "Access card": "Cartão de acesso",
    "Offline payment": "Pagamento offline",
    "Local music": "Música local",
    "Local gallery": "Galeria local",
    "E-book": "E-book",
    "Compass": "Bússola",
    "Navigation": "Navegação",
    "Mini games": "Minijogos"
  };

  const replacements = [
    [/\bCustom 500 pcs min\b/gi, "Personalizado a partir de 500 peças"],
    [/\bCustom order\b/gi, "Sob encomenda"],
    [/\bOut of Stock\b/gi, "Esgotado"],
    [/\bLow Stock\b/gi, "Estoque limitado"],
    [/\bIn Stock\b/gi, "Em estoque"],
    [/\bOpen-Ear Design\b/gi, "Design aberto"],
    [/\bHealth Monitoring\b/gi, "Monitoramento de saúde"],
    [/\bClassic Model\b/gi, "Modelo clássico"],
    [/\bVariants\b/gi, "variantes"],
    [/\bCold\/Hot Air\b/gi, "Ar frio/quente"],
    [/\bStyling Set\b/gi, "Kit de modelagem"],
    [/\bReady Stock\b/gi, "Estoque disponível"],
    [/\bMagnetic Cable\b/gi, "Cabo magnético"],
    [/\bSolar Camera Premium\b/gi, "Câmera solar premium"],
    [/\bSolar Camera Mid-Range\b/gi, "Câmera solar intermediária"],
    [/\bSolar Camouflage Camera\b/gi, "Câmera solar camuflada"],
    [/\bFeeding\/Bird Monitor\b/gi, "Monitor de alimentação/aves"],
    [/\b2-Way Audio\b/gi, "Áudio bidirecional"],
    [/\bMagnetic Charging\b/gi, "Carregamento magnético"],
    [/\bRetail Pack\b/gi, "Embalagem para varejo"],
    [/\bSports Camera Basic\b/gi, "Câmera esportiva básica"],
    [/\bSports Camera Advanced\b/gi, "Câmera esportiva avançada"],
    [/\bWaterproof\b/gi, "À prova d'água"],
    [/\bProfessional Grade\b/gi, "Nível profissional"],
    [/\bSingle Mode\b/gi, "Modo único"],
    [/\bWireless Charging\b/gi, "Carregamento sem fio"],
    [/\bHeart Rate\b/gi, "Frequência cardíaca"],
    [/\bReal-Time Translation\b/gi, "Tradução em tempo real"],
    [/\bIn-Ear Detection\b/gi, "Detecção no ouvido"],
    [/\bBattery Life\b/gi, "Autonomia da bateria"],
    [/\bCharging\b/gi, "Carregamento"],
    [/\bFeatures\b/gi, "Recursos"],
    [/\bScreen\b/gi, "Tela"],
    [/\bShell\b/gi, "Carcaça"],
    [/\bMode\b/gi, "Modo"],
    [/\bStandard\b/gi, "Padrão"],
    [/\bBasic\b/gi, "Básico"]
  ];

  function translate(value) {
    if (value === null || value === undefined) return '';
    const source = String(value);
    if (Object.prototype.hasOwnProperty.call(translations, source)) {
      return translations[source];
    }
    const encodedSource = source
      .replace(/&/g, '&amp;')
      .replace(/“/g, '&ldquo;')
      .replace(/”/g, '&rdquo;');
    if (Object.prototype.hasOwnProperty.call(translations, encodedSource)) {
      return translations[encodedSource];
    }
    return replacements.reduce(function (result, entry) {
      return result.replace(entry[0], entry[1]);
    }, source);
  }

  window.PT_BR_TRANSLATIONS = translations;
  window.translatePtBr = translate;
})();
